name: Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
jobs:
  opa-tests:
    name: conftest verify
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.25.0/conftest_0.25.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.25.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/
          conftest plugin install git://github.com/volanja/govc-conftest//govc
      - name: conftest verify
        run: |
          conftest verify --policy examples/datacenter/policy
